<div class="mx-5 d-none d-lg-block" id="brand">

    {{--    <div class="fw-bold text-center poppins p-0" style="font-size: 20px; line-height: 0.9;">Proudly partnering with these outstanding organizations</div>--}}
    <div class="row row-cols-3 row-cols-sm-3 row-cols-md-5 row-cols-lg-5">
        <div class="col p-0 d-flex align-items-center justify-content-center">
            <p class="text-muted mb-0 poppins mx-5" style="font-size: 20px;">Proudly partnering with these outstanding organizations</p>
        </div>
        <div class="col p-0 d-flex align-items-center justify-content-center"><a href="https://www.reedmusicstudios.com/" target="_blank" rel="noopener noreferrer" class="d-flex align-items-center justify-content-center" style="max-width: 100%;" aria-label="Reed Music Studios (opens in a new tab)"><x-site-image src="/images-mist/partner1.jpeg" alt="Reed Music Studios" width="320" height="219" loading="lazy" sizes="100vw" /></a></div>
        <div class="col p-0 d-flex align-items-center justify-content-center"><a href="https://www.viterbo.edu/" target="_blank" rel="noopener noreferrer" class="d-flex align-items-center justify-content-center" style="max-width: 100%;" aria-label="Viterbo University (opens in a new tab)"><x-site-image src="/images-mist/partner2.png" alt="Viterbo University" width="150" height="133" loading="lazy" sizes="100vw" /></a></div>
        <div class="col p-0 d-flex align-items-center justify-content-center"><a href="https://morethanjustgreatdancing.com/" target="_blank" rel="noopener noreferrer" class="d-flex align-items-center justify-content-center" style="max-width: 100%;" aria-label="More Than Just Great Dancing! (opens in a new tab)"><x-site-image src="/images-mist/partner3.png" alt="More Than Just Great Dancing!" width="400" height="67" loading="lazy" sizes="100vw" /></a></div>
        <div class="col p-0 d-flex align-items-center justify-content-center"><a href="https://www.lacrossesymphony.org/" target="_blank" rel="noopener noreferrer" class="d-flex align-items-center justify-content-center" style="max-width: 100%;" aria-label="La Crosse Symphony Orchestra (opens in a new tab)"><x-site-image src="/images-mist/partner4.png" alt="La Crosse Symphony Orchestra" width="300" height="67" loading="lazy" sizes="100vw" /></a></div>
        <div class="col p-0 d-flex align-items-center justify-content-center"><a href="https://www.chancetodancefoundation.org/" target="_blank" rel="noopener noreferrer" class="d-flex align-items-center justify-content-center" style="max-width: 100%;" aria-label="A Chance to Dance Foundation (opens in a new tab)"><x-site-image src="/images-mist/partner5.png" alt="A Chance to Dance Foundation" width="407" height="106" loading="lazy" sizes="100vw" /></a></div>
        <div class="col p-0 d-flex align-items-center justify-content-center"><x-site-image src="/images-mist/partner6.jpg" alt="Coulee Parenting Connection" width="300" height="106" loading="lazy" sizes="100vw" /></div>
        <div class="col p-0 d-flex align-items-center justify-content-center"><a href="https://www.webercenterarts.org/" target="_blank" rel="noopener noreferrer" class="d-flex align-items-center justify-content-center" style="max-width: 100%;" aria-label="Weber Center for the Performing Arts (opens in a new tab)"><x-site-image src="/images-mist/partner7.png" alt="Weber Center for the Performing Arts" width="282" height="73" loading="lazy" sizes="100vw" /></a></div>
        <div class="col p-0 d-flex align-items-center justify-content-center"><x-site-image src="/images-mist/partner8.jpg" alt="Ballet La Crosse" width="359" height="129" loading="lazy" sizes="100vw" /></div>
        <div class="col p-0 d-flex align-items-center justify-content-center"><a href="https://www.thewillowandgrace.com/" target="_blank" rel="noopener noreferrer" class="d-flex align-items-center justify-content-center" style="max-width: 100%;" aria-label="Willow &amp; Grace Boutique (opens in a new tab)"><x-site-image src="/images-mist/partner9.png" alt="Willow &amp; Grace Boutique" width="800" height="96" loading="lazy" sizes="100vw" /></a></div>
    </div>
</div>
